# Dev profile: use H2 in-memory so the app can run offline for development
spring.datasource.url=jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Limite de upload de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Use H2 dialect and allow schema auto-update during dev
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Configuração do MinIO para Dev ---
minio.url=http://s3.davidson.dev.br
minio.access-key=java-api
minio.secret-key=sua_key_aqui
minio.bucket-name=portfolio-image

# Admin user for dev profile
app.admin.username=admin
app.admin.password=adminpass

# Redis Cache
REDIS_HOST=ip_do_redis(exemplo:192.168.0.51)
REDIS_PORT=porta_do_redis(padrão 6379)
REDIS_PASSWORD='sua_senha_aqui'

# Integra    o Telegram
telegram.bot.token=Seu_tokem_aqui
telegram.chat.id=Seu_chat_id_aqui
